#ifndef TAG_H
#define TAG_H

#define MAIN_MASTER_RANK 		0
#define SIEVE_MASTER_RANK 		1
#define SIEVE_SLAVES_RANK_START 	SIEVE_MASTER_RANK + 1
// #define SIEVE_SLAVES_COUNT 		4
#define PALINDROME_MASTER_RANK 		SIEVE_SLAVES_RANK_START + SIEVE_SLAVES_COUNT
#define PALINDROME_SLAVES_RANK_START 	PALINDROME_MASTER_RANK + 1
// #define PALINDROME_SLAVES_COUNT 	4
#define PARSER_SMALL_RANK		PALINDROME_SLAVES_RANK_START + PALINDROME_SLAVES_COUNT
#define PARSER_BIG_RANK			PARSER_SMALL_RANK + 1
#define TOTAL_RANKS 			5 + SIEVE_SLAVES_COUNT + PALINDROME_SLAVES_COUNT

#define TAG_PALINDROME_FINISHED		1
#define TAG_SIEVE_FINISHED 		2
#define TAG_PALINDROME_DONE 		3
#define TAG_PRIME_ANSWER 		4
#define TAG_PARSER_FINISHED 		5
#define TAG_PRIME_QUESTION 		6
#define TAG_RUN_PALINDROME 		7
#define TAG_KILL 			8

#endif
