/**
 * Includes.
 */
#include <pthread.h>
#include <cstdio>
#include <ctime>
#include <cstring>
#include <errno.h>
#include <cstring>
#include <climits>

/**
 * Defines.
 */
#define LL long long // Long long alias.
#define M 1000000000 // Number of iterations.
#define N 50 // Number of threads, N should divide M!

pthread_t threads[N]; // PThreads objects.
LL area[N]; // Areas counter, number of points inside the area, we use this to avoid mutexes (more overhead).

const int A = 1103515245, C = 12345; // Parameters of the linear random number generator.
const LL T = (LL)INT_MAX*INT_MAX; // The bounding position of the outter square.

/**
 * Generates the next random number.
 */
int next(int& x)
{
	return x = x*A+C;
}

/**
 * Thread function.
 */
void* function(void* ptr)
{
	LL a, b, cntr, lim = M/N; // lim is the number of iterations.
	int i, x = time(NULL);
	memcpy(&i, &ptr, sizeof(i)); // Getting the index of the area array we need to use.
	
	// Monte Carlo loop.
	for (cntr = 0; cntr < lim; ++cntr)
	{
		a = next(x);
		b = next(x);
		if (a*a + b*b <= T) ++area[i]; // Checking if the point is inside the circle.
	}
	
	return NULL;
}

/**
 * Main.
 */
int main()
{
	// Creating threads.
	for (int i = 0; i < N; ++i)
	{
		pthread_attr_t attr;
		pthread_attr_init(&attr);
		pthread_attr_setstacksize(&attr, 1000); // Setting max stack of the thread to 1KB.
		if (pthread_create(&threads[i], &attr, function, (void*)i) == -1)
			printf("%s\n", strerror(errno)); // Check for errors.
	}
	
	LL res = 0; // Sum of the areas calculated by each thread.
	for (int i = 0; i < N; ++i)
	{
		pthread_join(threads[i], NULL); // Wait for the i thread end.
		res += area[i]; // Add to res the value generated by the i thread.
	}
	
	printf("%lld\n", res*4); // The way this is calculated is explained on the docs.
	
	return 0;
}

